displayName=GPS Bookmarks
author=Makeshift
description=Save and navigate to your favourite world locations. Integrates with the Shortest Path plugin.
tags=gps,bookmark,navigation,shortestpath,location
version=
plugins=com.gpsbookmark.GpsBookmarkPlugin
build=standard
